import streamlit as st
from PIL import Image
import numpy as np

st.set_page_config(
    page_title="AI Knee Assessment",
    page_icon="🦵",
    layout="wide"
)

st.title("🦵 AI-Assisted Knee Assessment System")
st.write(
    "AI-assisted analysis of knee medical images for anatomical "
    "measurement and personalized implant planning."
)

st.info(
    "Prototype/Demo only — measurements shown by this application "
    "are not intended for clinical diagnosis."
)

uploaded_file = st.file_uploader(
    "Upload a knee medical image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.subheader("Uploaded Knee Image")
    st.image(image, use_container_width=True)

    image_array = np.array(image)

    st.subheader("Anatomical Analysis")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Femur", "Detected")
    
    with col2:
        st.metric("Tibia", "Detected")
    
    with col3:
        st.metric("Medial Meniscus", "Detected")

    st.subheader("Quantitative Measurements")

    # Demo values for prototype interface.
    # Replace these with measurements generated by a trained
    # segmentation/model pipeline.
    femur_length = st.number_input(
        "Femoral dimension (mm)",
        min_value=0.0,
        value=45.0
    )

    tibia_length = st.number_input(
        "Tibial dimension (mm)",
        min_value=0.0,
        value=40.0
    )

    meniscus_thickness = st.number_input(
        "Medial meniscus thickness (mm)",
        min_value=0.0,
        value=4.0
    )

    if st.button("Analyze Knee"):

        st.success("Analysis completed.")

        st.write("### Results")

        results = {
            "Femoral Dimension": f"{femur_length:.2f} mm",
            "Tibial Dimension": f"{tibia_length:.2f} mm",
            "Meniscus Thickness": f"{meniscus_thickness:.2f} mm"
        }

        for name, value in results.items():
            st.write(f"**{name}:** {value}")

        st.subheader("Implant Database Comparison")

        implant_sizes = {
            "Implant A": 40,
            "Implant B": 45,
            "Implant C": 50,
            "Implant D": 55
        }

        closest_implant = min(
            implant_sizes,
            key=lambda x: abs(implant_sizes[x] - femur_length)
        )

        st.write(
            f"**Closest prototype implant size:** {closest_implant}"
        )

        st.warning(
            "This implant suggestion is a software prototype result "
            "and must not be used for real patient treatment."
        )

else:
    st.write(
        "Upload a knee image to begin the assessment."
    )
